import './globals.css'
import Navbar from './components/Navbar'
import Search from './components/Search'
import { ContextProvider } from './ContextProvider'
import Footer from './components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`flex flex-col justify-between`}>
        <ContextProvider>
          <Navbar />
          <Search />
          {children}
          <Footer />
        </ContextProvider>
      </body>
    </html>
  )
}
