import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Search from './components/Search'
import { ContextProvider } from './ContextProvider'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col justify-between`}>
        <ContextProvider>
          <Navbar />
          <Search />
          {children}
          <Footer />
        </ContextProvider>
      </body>
    </html>
  )
}
